"""add cascade mode

Revision ID: c6cc28858ea4
Revises: 880054d1960b
Create Date: 2024-12-26 23:31:16.916912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6cc28858ea4"
down_revision: Union[str, None] = "880054d1960b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chat_user_id_fkey", "chat", type_="foreignkey")
    op.create_foreign_key(None, "chat", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("message_chat_id_fkey", "message", type_="foreignkey")
    op.create_foreign_key(
        None, "message", "chat", ["chat_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message", type_="foreignkey")
    op.create_foreign_key(
        "message_chat_id_fkey", "message", "chat", ["chat_id"], ["id"]
    )
    op.drop_constraint(None, "chat", type_="foreignkey")
    op.create_foreign_key("chat_user_id_fkey", "chat", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###
