"""Fix relationship 

Revision ID: 880054d1960b
Revises: 48629c54f97a
Create Date: 2024-12-26 21:11:52.051270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "880054d1960b"
down_revision: Union[str, None] = "48629c54f97a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "chat", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat", type_="foreignkey")
    # ### end Alembic commands ###
